apiVersion: v1
kind: Service
metadata:
  name: {{ template "lnd.fullname" . }}-internal
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: rest
      port: {{ .Values.internalServices.restExternalPort }}
      targetPort: rest
    - name: rpc
      port: {{ .Values.internalServices.rpcExternalPort }}
      targetPort: rpc
  selector:
    app: {{ template "lnd.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "lnd.fullname" . }}-external
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - name: p2p
      port: {{ .Values.externalServices.p2pExternalPort }}
      targetPort: p2p
  selector:
    app: {{ template "lnd.name" . }}
    release: {{ .Release.Name }}
